# Configue a default setup of Home Assistant (frontend, api, ets.)

tts:
  - platform: google_translate

sensor:
  - platform: mqtt
    name: "Temperature"
    state_topic: "door/temperature"
    unit_of_measurement: '°F'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "Humidity"
    state_topic: "door/humidty"
    unit_of_measurement: '%'
    value_template: "{{ value_json.relative_humity }}"
 
binary_sensor:
  - platform: mqtt
    name: Movment
    state_topic: "door/pir"
    payload_on: "1"
    payload_off: "0"
 
switch:
  - platform: mqtt
    name: Door
    command_topic: "door/switch1"
    state_topic: "door/switch1"
    payload_on: "1"
    payload_off: "0"
    state_on: "1"
    state_off: "0"
